apiVersion: v1
kind: Service
metadata:
  name: mapeados-service
  namespace: mperezco
  labels:
    app: mapeados-service
spec:
  # Usa el selector para encontrar los pods con la etiqueta 'app: decrypt-service'
  selector:
    app: mapeados-service
  ports:
    # El puerto que otros servicios usarán para acceder a este servicio
    - name: http
      port: 8091
      # El puerto interno del contenedor (debe coincidir con containerPort del Deployment)
      targetPort: 8080
  type: ClusterIP # Acceso interno, ideal para comunicación servicio-a-servicio