apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: perlanegra
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-12-02T11:15:33Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: mariadb
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/part-of: mariadb
    name: data-mariadb-0
    namespace: mperezco
    resourceVersion: "158233"
    uid: be9c1c05-6ddb-4bae-9aa7-5945cc3ce518
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-be9c1c05-6ddb-4bae-9aa7-5945cc3ce518
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"redpanda-data-pvc","namespace":"mperezco"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: perlanegra
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-12-01T16:49:52Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: redpanda-data-pvc
    namespace: mperezco
    resourceVersion: "125909"
    uid: a14ce7f7-54b0-4a37-8d2a-90ddfedbcf8b
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-a14ce7f7-54b0-4a37-8d2a-90ddfedbcf8b
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
