apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redpanda-bootstrap","namespace":"mperezco"},"spec":{"ports":[{"name":"kafka-broker","port":9092,"protocol":"TCP","targetPort":9092}],"selector":{"app":"redpanda-single"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-02T13:53:54Z"
  name: redpanda-bootstrap
  namespace: mperezco
  resourceVersion: "167259"
  uid: 47d29d96-f162-4105-b5ef-9acb3be60dd1
spec:
  clusterIP: 10.43.125.116
  clusterIPs:
  - 10.43.125.116
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: kafka-broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: redpanda-single
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
