apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mariadb
    meta.helm.sh/release-namespace: mperezco
  creationTimestamp: "2025-12-02T11:15:33Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/version: 12.1.2
    helm.sh/chart: mariadb-24.0.0
  name: mariadb
  namespace: mperezco
  resourceVersion: "158199"
  uid: 15a23915-c06f-4d8c-a5be-e32300dc0d50
spec:
  clusterIP: 10.43.4.107
  clusterIPs:
  - 10.43.4.107
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
